defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = '../md-pdf/en'
    languageName = "English"
    languageCode = "en"
    flag = "flag-us"
    weight = 1
  [languages.es]
    contentDir = '../md-pdf/es'
    languageName = "Español"
    languageCode = "es"
    flag = "flag-es"
    weight = 2
  [languages.ko]
    contentDir = '../md-pdf/ko'
    languageName = "Korean"
    languageCode = "ko"
    flag = "flag-ko"
    weight = 3
  [languages.fr]
    contentDir = '../md-pdf/fr'
    languageName = "Français"
    languageCode = "fr"
    flag = "flag-fr"
    weight = 4
  [languages.ar]
    contentDir = '../md-pdf/ar'
    languageName = "عربي"
    languageCode = "ar"
    flag = "flag-ar"
    weight = 5
  [languages.id]
    contentDir = '../md-pdf/id'
    languageName = "Indonesian"
    languageCode = "id"
    flag = "flag-id"
    weight = 6
  [languages.ja]
    contentDir = '../md-pdf/ja'
    languageName = "Japanese"
    languageCode = "ja"
    flag = "flag-ja"
    weight = 7
  [languages.ru]
    contentDir = '../md-pdf/ru'
    languageName = "Русский"
    languageCode = "ru"
    flag = "flag-ru"
    weight = 8
  [languages.pt]
    contentDir = '../md-pdf/pt'
    languageName = "Portuguese"
    languageCode = "pt"
    flag = "flag-pt"
    weight = 9
  [languages.zh]
    contentDir = '../md-pdf/zh'
    languageName = "简体中文"
    languageCode = "zh"
    flag = "flag-zh"
    weight = 10

[params]
hide_lang_switcher = true
