name: Hugo-CI
on:
  push:
    branches:
      - develop-deploy-test
#    paths-ignore:
#        '.github/**'
jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-pdf]
    steps:
      - name: hugo build
        run: |
          cd aspose-pdf-docs
          git clone --single-branch --branch develop-deploy-test https://github.com/aspose-pdf/Aspose.PDF-Documentation.git || (cd Aspose.PDF-Documentation && git pull)
          git clone --single-branch --branch master https://git.dev.dynabic.com/containerize-hugo/lutsk-aspose-prototype.git || (cd lutsk-aspose-prototype && git pull)
          cd lutsk-aspose-prototype
          git clone --single-branch --branch master https://git.dev.dynabic.com/containerize-hugo/lutsk-aspose-theme.git themes/lutsk-aspose-theme || (cd themes/lutsk-aspose-theme && git pull)
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
          rm -rf public
          hugo --minify --baseURL https://docs-qa.aspose.com/pdf
      - name: hugo deploy
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          script: |
            aws --debug s3 sync aspose-pdf-docs/lutsk-aspose-prototype/public/ s3://docs-qa.aspose.com/pdf/
          run: |
            pwd
